### ISSUE TITLE
Adding Lights doesn’t work anymore

### ISSUE THREAD

**Issue by joeblack2k** [fantomnotabene/HomeyCONZ#23] opened 2019-12-19 23:40 UTC
hey, i’m trying to add lights the Phillips Playbar and the Philips Bloom light but i get a “Timeout after 3000 seconds” how do i get some info to see whats happening?

**Comment by joeblack2k** [comment] 2019-12-20 10:44
https://www2.meethue.com/en-gb/p/hue-white-and-colour-ambience-iris-table-lamp/7199960PU

That one is the trouble maker, removed it from deconz and everything is working again

**Comment by notabene00** [comment] 2019-12-20 12:48
> how do i get some info to see whats happening

- `athom app run`
- try to add light
- copy&paste stacktrace here

**Comment by notabene00** [comment] 2019-12-20 13:14
Possible duplicate of #21

**Comment by joeblack2k** [comment] 2019-12-20 16:46
it does work with app run... i see all lights waiting to be added ..

wen canceling and installing the app again.. it hangs again

**Comment by joeblack2k** [comment] 2019-12-21 09:28
I installed the Hue Iris with “athom app run” and then it works but there is no way todo colors only on/off and dim but in philips hue app it has colors..

**Comment by notabene00** [comment] 2019-12-21 12:07
Just to be clear: is this light have no color picker at all?
Or you can't change color by tapping on it?

**Comment by joeblack2k** [comment] 2019-12-21 16:48
No color picker at all

**Comment by joeblack2k** [comment] 2019-12-21 16:51
![448D21F1-0F7B-469B-8380-FDB6B577573C](https://user-images.githubusercontent.com/3456102/71310930-717d2d00-241a-11ea-89bd-3c4c2b4c662d.png)

**Comment by notabene00** [comment] 2019-12-22 17:18
> No color picker at all

Can you find type of these lights recognized by deCONZ?
Should be "Extended color light"

Or maybe this is the type that is not implemented yet

**Comment by joeblack2k** [comment] 2019-12-22 20:58
As you can see Phoconz supports it

![BD9BF2FB-21D0-4492-B7CD-B307ECF2619F](https://user-images.githubusercontent.com/3456102/71327225-31937400-2506-11ea-8c51-1e89cdeffb6b.jpeg)

**Comment by notabene00** [comment] 2019-12-22 21:00
Yes, but what type declared for this light?

**Comment by notabene00** [comment] 2019-12-23 12:13
```javascript
[
  'On/Off light',
  'Dimmable light',
  'Color temperature light',
  'Extended color light',
  'Smart plug',
  'On/Off plug-in unit',
  'Window covering device',
]
```
are supported (color with reservations)

Maybe there are more types
So the app can't realise what type to use

**Comment by notabene00** [comment] 2019-12-23 12:36
> it does work with app run... i see all lights waiting to be added ..
> 
> wen canceling and installing the app again.. it hangs again

It seems I can't influence it
You're running app in two ways
First: `install` installs app to homey and exit
Second: `run` runs app and attaches debugger (shows you logs)
And you're getting different results
But the app code is the same in both cases

So I think this issue should be closed now
Since you have added the light and for me adding (including color) lights working fine
![IMG_7133EC13FE41-1](https://user-images.githubusercontent.com/9576189/71358419-e62aa580-2599-11ea-93d9-b0a8ad6fe87b.jpeg)

Please, open new issue for `no color picker for color light` problem

**Closed as completed by notabene00** 2019-12-23 12:36 UTC
Labels: bug
