### ISSUE TITLE
Trådfri color light

### ISSUE THREAD

**Issue by k4mrat** [fantomnotabene/HomeyCONZ#21] opened 2019-12-17 10:58 UTC
**Describe the bug:**
When Trådfri color bulbs are present in Deconz and I try to add any light, color or ordinary, via homeyconz it becomes unresponsive and unable to add any light. It will often say that it can’t find any lights and time out, when I kept trying to add them i crashed the app after a few attempts and had to restart it. As soon as colored light was removed from deconz the app works and can add lights again.

**Comment by notabene00** [comment] 2019-12-20 13:14
You can try [this](https://github.com/fantomnotabene/HomeyCONZ/issues/23#issuecomment-567913674)

**Comment by k4mrat** [comment] 2019-12-20 13:16
Great! I’ll get on that asap!

**Comment by notabene00** [comment] 2019-12-26 14:18
@k4mrat ping)

**Comment by k4mrat** [comment] 2020-01-03 14:35
Hey, sorry for the delay, been on a well needed christmas/new year vacation.
When doing "app run" i can add the light and on/off works, but with this.

> 2020-01-03 15:04:41 [log] [ManagerDrivers] [lamp] [5] Color light 16 has been initiated
2020-01-03 15:05:15 [log] [deCONZ] state update for Color light 16 { alert: null,
  bri: 254,
  colormode: 'xy',
  hue: 0,
  on: false,
  reachable: true,
  sat: 0,
  xy: [ 0.458, 0.41 ] }
(node:9670) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process
(node:9670) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9670) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9670) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process
(node:9670) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9670) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process
(node:9670) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
2020-01-03 15:05:17 [log] [deCONZ] state update for Color light 16 { alert: null,
  bri: 254,
  colormode: 'xy',
  hue: 0,
  on: true,
  reachable: true,
  sat: 0,
  xy: [ 0.458, 0.41 ] }
(node:9670) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process
(node:9670) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:9670) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process
(node:9670) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:9670) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process


The weird thing is that the color light seems to work now and can be added and used with basic functionality now (on/off) when running the app with "app install" as well. That same light caused the app to crash earlier.

**Comment by notabene00** [comment] 2020-01-07 11:06
No ability to change color is related to unimplemented `xy` color mode, I guess
Will try to fix it soon
Since adding the light is working this issue is duplicate of #28

**Comment by notabene00** [comment] 2020-01-07 11:19
So I'm closing this now

**Closed as completed by notabene00** 2020-01-07 11:19 UTC
Labels: bug
